# Generated by Django 5.1.4 on 2026-09-07 13:32

import apps.users.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='email address')),
                ('full_name', models.CharField(max_length=180, verbose_name='full name')),
                ('phone', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number in E.164 format, e.g. +919820012345.', regex='^\\+?[1-9]\\d{7,14}$')], verbose_name='phone')),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('vendor', 'Vendor / Atelier Partner'), ('tailor', 'Master Tailor'), ('stylist', 'Personal Stylist'), ('staff', 'Operations Staff'), ('admin', 'Administrator')], db_index=True, default='customer', max_length=16, verbose_name='role')),
                ('preferences', models.JSONField(blank=True, default=dict, help_text='Free-form storefront preferences, e.g. {"hide_model_faces": true, "default_currency": "INR"}.', verbose_name='preferences')),
                ('email_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='email verified at')),
                ('phone_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='phone verified at')),
                ('accepted_terms_at', models.DateTimeField(blank=True, null=True, verbose_name='accepted terms at')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ('-created_at',),
            },
            managers=[
                ('objects', apps.users.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('shipping', 'Shipping'), ('billing', 'Billing')], default='shipping', max_length=10)),
                ('recipient_name', models.CharField(max_length=180)),
                ('phone', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number in E.164 format, e.g. +919820012345.', regex='^\\+?[1-9]\\d{7,14}$')])),
                ('line1', models.CharField(max_length=255)),
                ('line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=120)),
                ('state_code', models.CharField(blank=True, db_index=True, max_length=8)),
                ('postal_code', models.CharField(max_length=16)),
                ('country_code', models.CharField(db_index=True, default='IN', max_length=2)),
                ('gstin', models.CharField(blank=True, help_text='Optional B2B GSTIN for input tax credit.', max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid 15-character GSTIN.', regex='^\\d{2}[A-Z]{5}\\d{4}[A-Z]{1}[A-Z\\d]{1}Z[A-Z\\d]{1}$')])),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'addresses',
                'ordering': ('-is_default', '-created_at'),
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_active'], name='user_role_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user', 'kind'), name='unique_default_address_per_kind'),
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.CheckConstraint(condition=models.Q(('country_code__regex', '^[A-Z]{2}$')), name='address_country_code_is_iso_alpha2'),
        ),
    ]
