# Generated by Django 5.1.4 on 2026-09-07 14:23

import apps.media_assets.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('product', 'Product image'), ('review', 'Customer review photo'), ('lookbook', 'Lookbook / editorial'), ('vendor_doc', 'Vendor document')], default='product', max_length=12)),
                ('original', models.FileField(max_length=512, upload_to=apps.media_assets.models.private_upload_path)),
                ('derivative', models.FileField(blank=True, max_length=512, null=True, upload_to=apps.media_assets.models.public_upload_path)),
                ('checksum', models.CharField(db_index=True, max_length=64)),
                ('content_type', models.CharField(max_length=64)),
                ('byte_size', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('moderation_status', models.CharField(choices=[('pending', 'Pending processing'), ('processing', 'Processing'), ('needs_review', 'Needs human review'), ('approved', 'Approved for publication'), ('rejected', 'Rejected'), ('failed', 'Processing failed')], db_index=True, default='pending', max_length=14)),
                ('faces_detected', models.PositiveSmallIntegerField(default=0)),
                ('blur_verified', models.BooleanField(default=False, help_text='Irreversibility check passed: variance collapsed inside every mask.')),
                ('exif_stripped', models.BooleanField(default=False)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_error', models.TextField(blank=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_assets', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['moderation_status', 'created_at'], name='asset_status_created_idx'), models.Index(fields=['kind', 'moderation_status'], name='asset_kind_status_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('moderation_status__in', ['pending', 'processing', 'needs_review', 'approved', 'rejected', 'failed'])), name='asset_status_valid'), models.CheckConstraint(condition=models.Q(models.Q(('moderation_status', 'approved'), _negated=True), models.Q(('blur_verified', True), ('derivative__isnull', False), models.Q(('derivative', ''), _negated=True)), _connector='OR'), name='asset_approved_requires_verified_derivative'), models.CheckConstraint(condition=models.Q(('byte_size__gt', 0)), name='asset_byte_size_positive')],
            },
        ),
    ]
