# Generated by Django 5.1.4 on 2026-09-07 14:23

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('path', models.CharField(db_index=True, editable=False, max_length=512)),
                ('depth', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('meta_title', models.CharField(blank=True, max_length=180)),
                ('meta_description', models.CharField(blank=True, max_length=320)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalog.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ('display_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('garment_type', models.CharField(choices=[('suit_set', 'Suit / Kameez set'), ('dress_material', 'Unstitched dress material'), ('lehenga', 'Lehenga'), ('sharara', 'Sharara'), ('gharara', 'Gharara'), ('farshi_palazzo', 'Farshi palazzo'), ('farshi_salwar', 'Farshi salwar'), ('palazzo', 'Palazzo / Pants'), ('gown', 'Gown'), ('tail_gown', 'Tail gown'), ('blouse', 'Blouse'), ('jacket', 'Jacket'), ('long_jacket', 'Long jacket'), ('dupatta', 'Dupatta / Stole')], db_index=True, max_length=24)),
                ('fabric', models.CharField(choices=[('lawn', 'Lawn'), ('chiffon', 'Chiffon'), ('organza', 'Organza'), ('georgette', 'Georgette'), ('velvet', 'Velvet'), ('silk', 'Silk'), ('raw_silk', 'Raw silk'), ('banarasi', 'Banarasi'), ('cotton', 'Cotton'), ('linen', 'Linen'), ('net', 'Net'), ('tissue', 'Tissue'), ('crepe', 'Crepe'), ('jacquard', 'Jacquard')], db_index=True, max_length=16)),
                ('work_type', models.CharField(choices=[('plain', 'Plain / Unembellished'), ('zardozi', 'Zardozi'), ('gota_patti', 'Gota patti'), ('mirror', 'Mirror / Sheesha'), ('chikankari', 'Chikankari'), ('mukaish', 'Mukaish'), ('resham', 'Resham thread'), ('sequin', 'Sequin'), ('dabka', 'Dabka'), ('printed', 'Printed'), ('block_print', 'Block print')], db_index=True, default='plain', max_length=16)),
                ('occasion', models.CharField(choices=[('bridal', 'Bridal'), ('mehndi', 'Mehndi'), ('nikah', 'Nikah'), ('walima', 'Walima'), ('eid', 'Eid'), ('party', 'Party'), ('formal', 'Formal'), ('casual', 'Casual / Daily')], db_index=True, max_length=12)),
                ('description', models.TextField(blank=True)),
                ('care_instructions', models.TextField(blank=True)),
                ('country_of_origin', models.CharField(default='IN', max_length=2)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, help_text='Strike-through price. Must exceed base_price when set.', max_digits=12, null=True)),
                ('hsn_code', models.CharField(db_index=True, max_length=8, validators=[django.core.validators.RegexValidator(message='HSN/SAC codes are 4 to 8 digits.', regex='^\\d{4,8}$')])),
                ('gst_rate_override', models.DecimalField(blank=True, decimal_places=0, help_text='Only where the HSN slab genuinely does not apply. Validated against the GST regime in force.', max_digits=4, null=True)),
                ('is_opaque', models.BooleanField(db_index=True, default=True, help_text='Fabric is not see-through.')),
                ('has_full_lining', models.BooleanField(db_index=True, default=False)),
                ('slit_coverage', models.CharField(choices=[('none', 'No slit'), ('ankle', 'Ankle-height slit'), ('mid_calf', 'Mid-calf slit'), ('knee', 'Knee-height slit'), ('thigh', 'Thigh-height slit')], db_index=True, default='none', max_length=10)),
                ('sleeve_coverage', models.CharField(choices=[('sleeveless', 'Sleeveless'), ('cap', 'Cap sleeve'), ('short', 'Short sleeve'), ('elbow', 'Elbow length'), ('three_quarter', 'Three-quarter'), ('full', 'Full length'), ('extra_long', 'Extra long')], db_index=True, default='full', max_length=14)),
                ('neckline_modesty', models.CharField(choices=[('deep', 'Deep'), ('moderate', 'Moderate'), ('high', 'High'), ('closed', 'Closed / Collared')], default='moderate', max_length=10)),
                ('back_coverage', models.CharField(choices=[('open', 'Open back'), ('deep', 'Deep back'), ('moderate', 'Moderate'), ('full', 'Fully covered')], default='full', max_length=10)),
                ('requires_slip', models.BooleanField(default=False)),
                ('is_sheer_overlay_only', models.BooleanField(default=False)),
                ('supports_bespoke', models.BooleanField(db_index=True, default=False)),
                ('bespoke_surcharge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('stitching_days', models.PositiveSmallIntegerField(default=0, help_text='Atelier lead time in days for a bespoke order.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('active', 'Active'), ('out_of_stock', 'Out of stock'), ('archived', 'Archived')], db_index=True, default='draft', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=180)),
                ('meta_description', models.CharField(blank=True, max_length=320)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
                ('vendor', models.ForeignKey(limit_choices_to={'role__in': ['vendor', 'staff', 'admin']}, on_delete=django.db.models.deletion.PROTECT, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alt_text', models.CharField(max_length=200)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_images', to='media_assets.mediaasset')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product')),
            ],
            options={
                'ordering': ('display_order',),
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(db_index=True, max_length=64, unique=True)),
                ('size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL'), ('FREE', 'Free size'), ('CUSTOM', 'Made to measure')], max_length=8)),
                ('colour', models.CharField(max_length=60)),
                ('colour_hex', models.CharField(blank=True, max_length=7)),
                ('price_delta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Added to the product base price. May be negative.', max_digits=10)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('low_stock_threshold', models.PositiveIntegerField(default=2)),
                ('weight_grams', models.PositiveIntegerField(default=0, help_text='Used for shipping rate calculation.')),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product')),
            ],
            options={
                'ordering': ('product', 'size', 'colour'),
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['path', 'is_active'], name='category_path_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.CheckConstraint(condition=models.Q(('depth__lte', 4)), name='category_depth_max_4'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'category'], name='product_status_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_opaque', 'has_full_lining', 'slit_coverage'], name='product_modesty_facet_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['occasion', 'status'], name='product_occasion_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['base_price'], name='product_price_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('base_price__gte', Decimal('0.00'))), name='product_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('bespoke_surcharge__gte', Decimal('0.00'))), name='product_bespoke_surcharge_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('compare_at_price__isnull', True), ('compare_at_price__gt', models.F('base_price')), _connector='OR'), name='product_compare_at_exceeds_base'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('supports_bespoke', False), ('stitching_days__gt', 0), _connector='OR'), name='product_bespoke_requires_lead_time'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('is_sheer_overlay_only', False), ('is_opaque', False), _connector='OR'), name='product_sheer_overlay_not_opaque'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('slit_coverage__in', ['none', 'ankle', 'mid_calf', 'knee', 'thigh'])), name='product_slit_coverage_valid'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('sleeve_coverage__in', ['sleeveless', 'cap', 'short', 'elbow', 'three_quarter', 'full', 'extra_long'])), name='product_sleeve_coverage_valid'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('neckline_modesty__in', ['deep', 'moderate', 'high', 'closed'])), name='product_neckline_valid'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('back_coverage__in', ['open', 'deep', 'moderate', 'full'])), name='product_back_coverage_valid'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'pending_review', 'active', 'out_of_stock', 'archived'])), name='product_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('product',), name='one_primary_image_per_product'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'is_active'], name='variant_product_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'size', 'colour'), name='unique_variant_per_product'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('stock_quantity__gte', 0)), name='variant_stock_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('size__in', ['XS', 'S', 'M', 'L', 'XL', 'XXL', 'XXXL', 'FREE', 'CUSTOM'])), name='variant_size_valid'),
        ),
    ]
