# Generated by Django 5.1.4 on 2026-09-07 14:23

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_number', models.CharField(db_index=True, max_length=24, unique=True)),
                ('guest_email', models.EmailField(blank=True, max_length=254)),
                ('guest_phone', models.CharField(blank=True, max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('placed', 'Placed'), ('payment_confirmed', 'Payment confirmed'), ('in_atelier', 'In atelier'), ('measurement_review', 'Measurement review'), ('stitching', 'Stitching'), ('quality_check', 'Quality check'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('return_requested', 'Return requested'), ('returned', 'Returned'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('place_of_supply_state', models.CharField(blank=True, max_length=8)),
                ('place_of_supply_country', models.CharField(default='IN', max_length=2)),
                ('supply_type', models.CharField(blank=True, choices=[('intra_state', 'Intra-state (CGST + SGST)'), ('inter_state', 'Inter-state (IGST)'), ('export', 'Zero-rated export')], max_length=12)),
                ('supply_date', models.DateField(blank=True, help_text='Date of supply. Selects the GST regime for this order forever.', null=True)),
                ('shipping_address', models.JSONField(default=dict)),
                ('billing_address', models.JSONField(default=dict)),
                ('customer_gstin', models.CharField(blank=True, max_length=15)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('discount_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('shipping_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('tax_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('placed_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('customer_notes', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(blank=True, help_text='Null for guest checkout.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orders.order')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(max_length=64)),
                ('product_name', models.CharField(max_length=200)),
                ('variant_label', models.CharField(blank=True, max_length=120)),
                ('hsn_code', models.CharField(max_length=8)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_bespoke', models.BooleanField(db_index=True, default=False)),
                ('modesty_snapshot', models.JSONField(blank=True, default=dict)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orders.order')),
                ('variant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_lines', to='catalog.productvariant')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderTaxSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('regime_name', models.CharField(max_length=120)),
                ('supply_type', models.CharField(choices=[('intra_state', 'Intra-state (CGST + SGST)'), ('inter_state', 'Inter-state (IGST)'), ('export', 'Zero-rated export')], max_length=12)),
                ('place_of_supply_state', models.CharField(blank=True, max_length=8)),
                ('place_of_supply_country', models.CharField(max_length=2)),
                ('state_gst_code', models.CharField(blank=True, max_length=4)),
                ('taxable_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cgst_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sgst_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('igst_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_zero_rated_export', models.BooleanField(default=False)),
                ('line_breakdown', models.JSONField()),
                ('rate_summary', models.JSONField(default=list)),
                ('notes', models.JSONField(default=list)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax_snapshot', to='orders.order')),
            ],
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='order_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', '-created_at'], name='order_customer_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'placed', 'payment_confirmed', 'in_atelier', 'measurement_review', 'stitching', 'quality_check', 'packed', 'shipped', 'delivered', 'return_requested', 'returned', 'refunded', 'cancelled'])), name='order_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('grand_total__gte', Decimal('0.00'))), name='order_grand_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('discount_total__gte', Decimal('0.00'))), name='order_discount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('customer__isnull', False), models.Q(('guest_email', ''), _negated=True), _connector='OR'), name='order_has_customer_or_guest_email'),
        ),
        migrations.AddIndex(
            model_name='orderevent',
            index=models.Index(fields=['order', '-created_at'], name='orderevent_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='orderline_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='orderline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', Decimal('0.00'))), name='orderline_unit_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='orderline',
            constraint=models.CheckConstraint(condition=models.Q(('discount__gte', Decimal('0.00'))), name='orderline_discount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='ordertaxsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('tax_total__gte', Decimal('0.00'))), name='taxsnapshot_tax_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='ordertaxsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('tax_total', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('cgst_total'), '+', models.F('sgst_total')), '+', models.F('igst_total')))), name='taxsnapshot_components_sum_to_total'),
        ),
        migrations.AddConstraint(
            model_name='ordertaxsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('grand_total', django.db.models.expressions.CombinedExpression(models.F('taxable_value'), '+', models.F('tax_total')))), name='taxsnapshot_grand_total_consistent'),
        ),
        migrations.AddConstraint(
            model_name='ordertaxsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_zero_rated_export', True), _negated=True), ('tax_total', Decimal('0.00')), _connector='OR'), name='taxsnapshot_export_is_zero_rated'),
        ),
    ]
