# Generated by Django 5.1.4 on 2026-09-07 14:23

import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BespokeFitProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(help_text="e.g. 'My measurements'", max_length=80)),
                ('measurements', models.JSONField(default=dict)),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('unit_system', models.CharField(choices=[('cm', 'Centimetres'), ('inch', 'Inches')], default='inch', max_length=4)),
                ('garment_type', models.CharField(blank=True, choices=[('suit_set', 'Suit / Kameez set'), ('dress_material', 'Unstitched dress material'), ('lehenga', 'Lehenga'), ('sharara', 'Sharara'), ('gharara', 'Gharara'), ('farshi_palazzo', 'Farshi palazzo'), ('farshi_salwar', 'Farshi salwar'), ('palazzo', 'Palazzo / Pants'), ('gown', 'Gown'), ('tail_gown', 'Tail gown'), ('blouse', 'Blouse'), ('jacket', 'Jacket'), ('long_jacket', 'Long jacket'), ('dupatta', 'Dupatta / Stole')], max_length=24)),
                ('measured_by', models.CharField(choices=[('self', 'Measured by customer'), ('tailor', 'Measured by Ferasha tailor'), ('stylist', 'Measured by stylist'), ('existing_garment', 'Copied from an existing garment')], default='self', max_length=18)),
                ('notes', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fit_profiles', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['tailor', 'stylist', 'staff', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_fit_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-is_default', '-updated_at'),
            },
        ),
        migrations.CreateModel(
            name='FitProfileRevision',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('revision', models.PositiveIntegerField()),
                ('measurements', models.JSONField()),
                ('preferences', models.JSONField(default=dict)),
                ('unit_system', models.CharField(max_length=4)),
                ('change_reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='tailoring.bespokefitprofile')),
            ],
            options={
                'ordering': ('-revision',),
            },
        ),
        migrations.CreateModel(
            name='TailoringOrderSpec',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('measurements', models.JSONField()),
                ('preferences', models.JSONField(default=dict)),
                ('unit_system', models.CharField(choices=[('cm', 'Centimetres'), ('inch', 'Inches')], max_length=4)),
                ('garment_type', models.CharField(choices=[('suit_set', 'Suit / Kameez set'), ('dress_material', 'Unstitched dress material'), ('lehenga', 'Lehenga'), ('sharara', 'Sharara'), ('gharara', 'Gharara'), ('farshi_palazzo', 'Farshi palazzo'), ('farshi_salwar', 'Farshi salwar'), ('palazzo', 'Palazzo / Pants'), ('gown', 'Gown'), ('tail_gown', 'Tail gown'), ('blouse', 'Blouse'), ('jacket', 'Jacket'), ('long_jacket', 'Long jacket'), ('dupatta', 'Dupatta / Stole')], max_length=24)),
                ('special_instructions', models.TextField(blank=True)),
                ('surcharge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('measurement_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('measurement_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_specs', to=settings.AUTH_USER_MODEL)),
                ('order_line', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tailoring_spec', to='orders.orderline')),
                ('source_profile', models.ForeignKey(blank=True, help_text='Provenance only. The authoritative values are in this row.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_specs', to='tailoring.bespokefitprofile')),
            ],
        ),
        migrations.AddIndex(
            model_name='bespokefitprofile',
            index=models.Index(fields=['user', '-updated_at'], name='fitprofile_user_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='bespokefitprofile',
            index=django.contrib.postgres.indexes.GinIndex(fields=['measurements'], name='fitprofile_measurements_gin'),
        ),
        migrations.AddConstraint(
            model_name='bespokefitprofile',
            constraint=models.UniqueConstraint(fields=('user', 'label'), name='unique_fit_profile_label_per_user'),
        ),
        migrations.AddConstraint(
            model_name='bespokefitprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user',), name='one_default_fit_profile_per_user'),
        ),
        migrations.AddConstraint(
            model_name='bespokefitprofile',
            constraint=models.CheckConstraint(condition=models.Q(('unit_system__in', ['cm', 'inch'])), name='fit_profile_unit_system_valid'),
        ),
        migrations.AddIndex(
            model_name='fitprofilerevision',
            index=models.Index(fields=['profile', '-revision'], name='revision_profile_idx'),
        ),
        migrations.AddConstraint(
            model_name='fitprofilerevision',
            constraint=models.UniqueConstraint(fields=('profile', 'revision'), name='unique_revision_per_profile'),
        ),
        migrations.AddIndex(
            model_name='tailoringorderspec',
            index=django.contrib.postgres.indexes.GinIndex(fields=['measurements'], name='spec_measurements_gin'),
        ),
        migrations.AddConstraint(
            model_name='tailoringorderspec',
            constraint=models.CheckConstraint(condition=models.Q(('surcharge__gte', Decimal('0.00'))), name='spec_surcharge_non_negative'),
        ),
    ]
